version: '3.9'

services:
  k6:
    image: loadimpact/k6
    environment:
    - K6_OUT=influxdb=http://influxdb:8086/k6
  influxdb:
    image: influxdb:1.8.10
    environment:
    - INFLUXDB_DB=k6
    - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    volumes:
    - ./data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    volumes:
    - ./data/grafana:/var/lib/grafana
    ports:
    - 3000:3000
